config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'welcome/index'

  root 'welcome#index'

  resources :articles

  resources :users

  resources :bicycles do
  	resources :rentals
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
	has_many :rentals, dependent: :destroy
	validates :serial, presence: true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :bicycle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController

  def index
    @bicycles = Bicycle.all
  end

  def show
    @bicycle = Bicycle.find(params[:id])
  end

  def new
    @bicycle = Bicycle.new
  end

  def edit
    @bicycle = Bicycle.find(params[:id])
  end

  def create
    @bicycle = Bicycle.new(bicycle_params)

    if@bicycle.save
      redirect_to @bicycle
    else
      render 'new'
    end
  end

  def update
    @bicycle = Bicycle.find(params[:id])

    if @bicycle.update(bicycle_params)
      redirect_to @bicycle
    else
      render 'edit'
    end
  end

  def destroy
    @bicycle = Bicycle.find(params[:id])
    @bicycle.destroy

    redirect_to bicycles_path
  end

  private
    def bicycle_params
      params.require(:bicycle).permit(:biketype, :brand, :model, :serial, :notes)
    end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
	
	def index
		@rentals = Rental.all
	end
	
	def show
		@rental = Rental.find(params[:id])
	end
	
	def new
		@rental = Rental.new
	end
	
	def edit
		@rental = Rental.find(params[:id])
	end
	
	def create
		@bicycle = Bicycle.find(params[:bicycle_id])
		@rental = @bicycle.rentals.create(rental_params)
		redirect_to bicycle_path(@bicycle)
	end
	
	def update
		@rental = Rental.find(params[:id])
		
		if @rental.update(rental_params)
			redirect_to @rental
		else
			render 'edit'
		end
	end
	
	def destroy
		@bicycle = Bicycle.find(params[:bicycle_id])
		@rental = Rental.find(params[:id])
		@rental.destroy
		
		redirect_to bicycle_path(@bicycle)
	end
				
	private
		def rental_params
			params.require(:rental).permit(:renter, :checkedout, :returned, :email, :phone, :locknum, :helmet)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bicycles/_form.html.erb
<%= form_for @bicycle do |f| %>
  
  <% if @bicycle.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@bicycle.errors.count, "error") %> prohibited this article from being saved: </h2>
      <ul>
        <% @bicycle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :type %><br>
      <!--<%= select_tag(:type, options_for_select([["road", "road"], ["mountain", "mountain"]], 2)) %>-->
      <select name="bicycle[biketype]" id="bicycle_biketype">
      <option value="road">Road</option>
      <option value="mountain">Mountain</option>
    </select>
  </p>

  <p>
    <%= f.label :brand %><br>
    <%= f.text_field :brand%>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_field :model%>
  </p>

  <p>
    <%= f.label :serial %><br>
    <%= f.text_field :serial%>
  </p>

  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes%>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/bicycles/edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>New Article</title>
</head>
<body>
<!-- header start --> 
 <table border='1'>
   <tr>
     <td><%= link_to 'Home', welcome_index_path %></td>
     <td><%= link_to 'Bicycles', bicycles_path %></td>
   </tr>
 </table>
<!-- header end --> 
<br>
<br>
<h3>New Article</h3>

<%= render 'form' %>

<%= link_to 'Back', bicycles_path %>

</body>
</html>

app/views/bicycles/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>View Articles</title>
</head>
<body>
<!-- header start --> 
 <table border='1'>
   <tr>
     <td><%= link_to 'Home', welcome_index_path %></td>
     <td><%= link_to 'Bicycles', bicycles_path %></td>
   </tr>
 </table>
<!-- header end --> 
<br>
<br>
<h3>List of Bicycles</h3>
<p><%= link_to 'New bicycle', new_bicycle_path %></p>
<table border='1'>
  <tr><th>Type</th><th>Brand</th><th>Model</th><th>Serial number</th></tr>

  <% @bicycles.each do |bicycle| %>
  <tr>
    <td><%= bicycle.biketype %></td>
    <td><%= bicycle.brand %></td>
    <td><%= bicycle.model %></td>
    <td><%= bicycle.serial %></td>
    <td><%= link_to 'Show', bicycle_path(bicycle) %></td>
    <td><%= link_to 'Edit', edit_bicycle_path(bicycle) %></td>
    <td><%= link_to 'Delete', bicycle_path(bicycle), method: :delete, data: {confirm: 'Are you sure?'} %></td>
  </tr>
  <% end %>
</table>

</body>
</html>

app/views/bicycles/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>New Bicycle</title>
</head>
<body>
<!-- header start --> 
 <table border='1'>
   <tr>
     <td><%= link_to 'Home', welcome_index_path %></td>
     <td><%= link_to 'Bicycles', bicycles_path %></td>
   </tr>
 </table>
<!-- header end --> 
<br>
<br>
<h3>New Bicycle</h3>

<%= render 'form' %>

<%= link_to 'Back', bicycles_path %>

</body>
</html>

app/views/bicycles/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>View Article</title>
</head>
<body>
<!-- header start --> 
 <table border='1'>
   <tr>
     <td><%= link_to 'Home', welcome_index_path %></td>
     <td><%= link_to 'Bicycles', bicycles_path %></td>
   </tr>
 </table>
<!-- header end --> 
<br>
<br>

<p>
  <strong>Type:</strong>
  <%= @bicycle.biketype %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @bicycle.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @bicycle.model %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @bicycle.serial %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @bicycle.notes %>
</p>

<h3>Rentals</h3>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Checkout<br>date</th>
    <th>Return<br>date</th>
    <th>Email address</th>
    <th>Phone number</th>
    <th>Lock<br>number</th>
    <th>Helmet</th>
  </tr>
  <% @bicycle.rentals.each do |rental| %>
  <tr>
    <td><%= rental.renter %></td>
    <td><%= rental.checkedout %></td>
    <td><%= rental.returned %></td>
    <td><%= rental.email %></td>
    <td><%= rental.phone %></td>
    <td><%= rental.locknum %></td>
    <td><%= rental.helmet ? "yes" : "no" %></td>
    <td><%= link_to 'Delete rental', [rental.bicycle, rental], method: :delete, data: {confirm: 'Are you sure?'} %>
  </tr>
  <% end %>
</table>

<h3>Add a rental:</h3>

<%= render 'rentals/form' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeInventoryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/_form.html.erb
<%= form_for([@bicycle, @bicycle.rentals.build]) do |f| %>
	<p>
		<%= f.label :renter %><br>
		<%= f.text_field :renter %>
	</p>
	<p>
		<%= f.label :checkedout %><br>
		<%= f.date_select :checkedout %>
	</p>
	<p>
		<%= f.label :returned %><br>
		<%= f.date_select :returned, :include_blank => true %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :phone %><br>
		<%= f.text_field :phone %>
	</p>
	<p>
		<%= f.label :locknum %><br>
		<%= f.text_field :locknum %>
	</p>
	<p>
		<%= f.label :helmet %><br>
		<%= f.check_box :helmet %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/rentals/_rental.html.erb
<table border="1">
  <tr>
    <th>Name</th>
    <th>Checkout<br>date</th>
    <th>Return<br>date</th>
    <th>Email address</th>
    <th>Phone number</th>
    <th>Lock<br>number</th>
    <th>Helmet</th>
  </tr>
  <!--<% @bicycle.rentals.each do |rental| %>-->
  <tr>
    <td><%= rental.renter %></td>
    <td><%= rental.checkedout %></td>
    <td><%= rental.returned %></td>
    <td><%= rental.email %></td>
    <td><%= rental.phone %></td>
    <td><%= rental.locknum %></td>
    <td><%= rental.helmet ? "yes" : "no" %></td>
    <td><%= link_to 'Delete rental', [rental.bicycle, rental], method: :delete, data: {confirm: 'Are you sure?'} %>
  </tr>
  <!--<% end %>-->
</table>

app/views/rentals/show.html.erb
<p>
	<strong>Brand:</strong>
	<%= @bicycle.brand %>
</p>

<p>
	<strong>Model:</strong>
	<%= @bicycle.model %>
</p>

<p>
	<strong>Type:</strong>
	<%= @bicycle.biketype %>
</p>

<h3>Add a rental:</h2>
<%= form_for([@bicycle, @bicycle.rentals.build]) do |f| %>
	<p>
		<%= f.label :renter %><br>
		<%= f.text_field :renter %>
	</p>
	<p>
		<%= f.label :checkedout %><br>
		<%= f.date_select :checkedout %>
	</p>
	<p>
		<%= f.label :returned %><br>
		<%= f.date_select :returned %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :phone %><br>
		<%= f.text_field :phone %>
	</p>
	<p>
		<%= f.label :locknum %><br>
		<%= f.text_field :locknum %>
	</p>
	<p>
		<%= f.label :helmet %><br>
		<%= f.check_box :helmet %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Edit', edit_bicycle_path(@bicycle) %> |
<%= link_to 'Back', bicycles_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Home</title>
</head>
<body>
<!-- header start --> 
 <table border='1'>
   <tr>
     <td><%= link_to 'Home', welcome_index_path %></td>
     <td><%= link_to 'Bicycles', bicycles_path %></td>
   </tr>
 </table>
<!-- header end --> 
<br>
<h3>Bicycle Inventory System</h3>
<h4>About</h4>
<p>Simple web application to record bicycles and rentals. Internet connection not required.
Click on the "bicycles" link above to get started.
<p>Created by Egan Dunning.
<h4>Links</h4>
<p><a href="http://www.plu.edu/recreations/outdoor-rec/bike_co-op/">PLU Bike Co-op website</a>
<p><a href="http://nashbar.com">Bike Nashbar</a> - for buying parts.
<p><a href="http://github.com/egandunning/BikeInventory_app">Source code</a>
</body>
</html>